name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true

    - name: Verify dependencies
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "go mod tidy resulted in changes. Please run 'go mod tidy' locally and commit the changes."
          git status
          git diff
          exit 1
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Format check
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files are not formatted correctly:"
          gofmt -l .
          echo "Please run 'go fmt ./...' locally and commit the changes."
          exit 1
        fi
